### ISSUE TITLE
Python TypeError when running the script

### ISSUE THREAD

**Issue by ItsLogic** [RickDB/PlexAniSync#125]
Just updated today as I wanted to use remote mappings but now when I try to run `python3 PlexAniSync.py` I get this error:
```
Traceback (most recent call last):
  File "PlexAniSync.py", line 10, in <module>
    import anilist
  File "/home/pi/PlexAniSync/anilist.py", line 9, in <module>
    from custom_mappings import AnilistCustomMapping
  File "/home/pi/PlexAniSync/custom_mappings.py", line 95, in <module>
    def get_custom_mapping_remote(file_mappings) -> List[tuple[str, str]]:
TypeError: 'type' object is not subscriptable
```

It is a brand new git clone and I am using the example custom_mappings.yaml and have edited config.ini with my details.
All the requirements are installed and I am using python 3.7.3 on Raspbian

**Comment by reconman** [comment]
I currently can only guarantee compatibility with python 3.10.

Old versions probably can't deal with the typing.

Can you update python?

**Comment by ItsLogic** [comment]
Updated to 3.10.4 and the script works fine now just like @karpik123 said although it was a bit of a hassle as raspbian repos dont have anything newer than 3.7.3.

Should probably update the requirements to specify the new python version (whatever that may be) required as it still lists 3.7 as compatible which it no longer is

**Comment by reconman** [comment]
The problem was the usage of `tuple` instead of `Tuple`. `tuple` is only valid for 3.9+.

Should work now for 3.7.
