### ISSUE TITLE
Help with Systemd AniPlexSync.service setup

### ISSUE THREAD

**Issue by GreenglassT** [RickDB/PlexAniSync#129]
Hello! I am trying to set up the Systemd service but I keep running into this error upon starting plex-ani-sync.service:

`Failed to start anilist-plex-sync.service: Unit anilist-plex-sync.service has a bad unit file setting.`

I understand that I have something wrong in my file, but I can't figure it out for the life of me.

Here is my plex-ani-sync.service file:

```
[Unit]
Description=One-shot execution of Plex to Anilist tracking sync

[Service]
Type=oneshot
User=pi
Group=pi
WorkingDirectory=/home/pi/PlexAniSync/
ExecStart=/usr/bin/python3 /home/pi/PlexAniSync/PlexAniSync.py
RemainAfterExit=no

[Install]
WantedBy=multi-user.target
```

PlexAniSync is in my home directory and the only users I have on my Pi are pi and plex. Do I need to change Group to something else?

PlexAniSync version: 1.3.18

**Comment by reconman** [comment]
I'm guessing that you need absolute directories instead of `~`.

**Comment by GreenglassT** [comment]
> So for a pi it could be /home/pi/PlexAniSync?

Still throwing me the same error

**Comment by reconman** [comment]
Can you update your initial description with your current version?

**Comment by GreenglassT** [comment]
Yep. I'm using the latest version 1.3.18.

**Comment by reconman** [comment]
Read my comment again. I wanted you to replace the systemd file content above with your current version.

**Comment by GreenglassT** [comment]
Ahhhhh okay okay.

**Comment by GreenglassT** [comment]
Updated :)

**Comment by reconman** [comment]
What happens if you run `/usr/bin/python3 /home/pi/PlexAniSync/PlexAniSync.py` as user `pi`?

**Comment by GreenglassT** [comment]
I get this error:

`[CONFIG] Settings file file not found: settings.ini`

**Comment by GreenglassT** [comment]
Sounds good. See you there in a second.

**Comment by reconman** [comment]
Problem was relative file paths in the service file and that the calendar expression in the timer didn't work on Raspberry Pi.
