### ISSUE TITLE
error on import configparser

### ISSUE THREAD

**Issue by eslamsidereel** [RickDB/PlexAniSync#13]
i followed the steps, but when i run PlexAniSync.py it keeps saying:

Traceback (most recent call last):
  File "PlexAniSync.py", line 2, in <module>
    import configparser
ImportError: No module named configparser

what could be causing this error?

**Comment by RickDB** [comment]
Looks like you skipped the installing of requirements:

https://github.com/RickDB/PlexAniSync/blob/master/README.md#step-4---install-requirements

Config parser among other requirements will then be installed.

**Comment by RickDB** [comment]
Good to hear 👍

**Comment by RickDB** [comment]
Tautulli requires Python 2 by default but you might run into old Python 2 reference right now, how I usually solve this is:

- Stop Tautulli
- Uninstall all Python versions
- Install Python 2.7 to C:\Python27 but don't select add to path in its installation options
- Install Python3 to C:\Python3 and select add to path in its installation options (make it the default)
- Restart Windows just in case there are some lingering path references
- Install PlexAniSync requirements again and do a quick test run
- Start Tautulli
- Setup the Tautulli sync script:

https://github.com/RickDB/PlexAniSync/wiki/Tautulli-sync-script

- Tautulli should now use Python 3 for its default script execution and report no errors, if it's still reports errors would post the Tautulli Notification logs

**Comment by eslamsidereel** [comment]
problem still persist this is the log
[tautulli.log](https://github.com/RickDB/PlexAniSync/files/3735497/tautulli.log)

**Comment by RickDB** [comment]
Could you run this command from within the PlexAniSync folder:

C:\Python27\Scripts\pip.exe install -r requirements.txt

**Comment by eslamsidereel** [comment]
the problem still persist 
![Capture](https://user-images.githubusercontent.com/45595948/67031170-41ab6380-f111-11e9-98b6-8116aaa2fb6f.PNG)
[tautulli.log](https://github.com/RickDB/PlexAniSync/files/3740486/tautulli.log)

I think it's a problem within Tautulli itself, cause i tried using a bat file containing "python PlexAniSync.py" placed in "C:\Tautulli\PlexAniSync". 
it works great when opened, but gives an error when i run it with tautulli.
[tautulli.log](https://github.com/RickDB/PlexAniSync/files/3740486/tautulli.log)

**Comment by RickDB** [comment]
It should work without the extra steps though and from that FAQ section not sure how that is possible in the Notification agents as that doesn't seem to allow for custom arguments.

For that batch script option try enclosing it with double or single quotes:

C:\Tautulli\PlexAniSync\PlexAniSync.bat "some series name"

Still not sure what could cause this as here it worked ootb with Python 2.7 and Python 3 installed next to each other, let me know if you can get it working and will add it to the wiki for other users.

**Comment by eslamsidereel** [comment]
OK I will try that and report back

**Comment by eslamsidereel** [comment]
Still no luck. I tried many things but the error persist. It seems that for some reason Tautulli is using python2 not python3 to run the script. I even tried overriding python2 in the argument section, but it didn't work. I checked the environment variables and made sure that python3 path installed not python2 and everything seems to be in place. I don't understand why it gives this error !!
[tautulli.log](https://github.com/RickDB/PlexAniSync/files/3744360/tautulli.log)

**Comment by RickDB** [comment]
Yeah that's a lib error due to Python 2 and 3 differences, not sure how to solve this but you could open an issue at Tautulli and ask for examples for running Python 3 scripts.
Can't replicate here still so hard to debug this locally.

**Comment by eslamsidereel** [comment]
maybe it's a problem within Tautulli itself. I will try to download an older version and run the script once more.

**Comment by RickDB** [comment]
Depending on how you start Tautuli can try starting Tautulli this way in case you haven't already:

- First install the requirements: C:\Python27\Scripts\pip.exe install -r requirements.txt
- Start Tautulli: C:\Python27\Python.exe Tautulli.py

That way at least it will have the requirements installed, it shouldn't error out on ConfigParser for 2.7 because that is available the (other libs we use it will).

**Comment by eslamsidereel** [comment]
I installed the requirements with python2 but the error still there

Tautulli Notifiers :: Script error:     Traceback (most recent call last):         File "C:\Tautulli\PlexAniSync\PlexAniSync.py", line 2, in <module>             import configparser     ImportError: No module named configparser
--
2019-10-18 23:26:52 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 1.
2019-10-18 23:26:52 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2019-10-18 23:26:52 | DEBUG | Tautulli Notifiers :: Full script is: ['python', 'C:\\Tautulli\\PlexAniSync\\PlexAniSync.py']
2019-10-18 23:26:52 | DEBUG | Tautulli Notifiers :: Trying to run notify script, action: test, arguments: []

**Comment by RickDB** [comment]
Very odd, no clue at the moment 😔

**Comment by eslamsidereel** [comment]
Yes 😕 I opened an issue in Tautulli support and they are trying to figure out the problem. 
If i found a solution to this error, I will post it here in detail.
Sorry for the trouble and Thank you 😄
