### ISSUE TITLE
[CONFIG] Settings file file not found: settings.ini

### ISSUE THREAD

**Issue by boopnbop** [RickDB/PlexAniSync#137]
When I type in the command -

> py C:\Users\[user]\Documents\PlexAniSync-master\PlexAniSync-master\PlexAniSync.py

to the command prompt, I am shot back with -

> 2022-05-29 15:21:07 [CONFIG] Settings file file not found: settings.ini

despite taking out the ".example" off of the end of the file name. It is also in the same folder as PlexAniSync.py so I don't understand why I am getting this error. What am I doing wrong?

**Comment by reconman** [comment]
Can you provide a screenshot of your PlexAniSync folder?

**Comment by reconman** [comment]
I think it's because your current working directory is not the PlexAniSync-master directory. Switch to that directory and then use `py PlexAniSync.py`.

**Comment by KaiserBh** [comment]
Try to cd into it first. 

You are running it from completely another directory.

So firt cd into it and run the PlexAniSync.py from that directory.
