### ISSUE TITLE
Unable to authenticate Plex Media Server

### ISSUE THREAD

**Issue by JulianDJ01** [RickDB/PlexAniSync#145]
I'm using the tautulli-plexanisync docker container to run this and looking through the logs PlexAniSync successfully connects to AniList and sees my existing series in my lists but won't connect to Plex.
```   2022-07-07 05:33:50 Unable to authenticate to Plex Media Server
    Traceback (most recent call last):
        File "/plexanisync/plexmodule.py", line 64, in authenticate
            plex = PlexServer(base_url, token, session)
        File "/app/lib/plexapi/server.py", line 116, in __init__
            data = self.query(self.key, timeout=self._timeout)
        File "/app/lib/plexapi/server.py", line 648, in query
            raise Unauthorized(message)
    plexapi.exceptions.Unauthorized: (401) unauthorized; http://192.168.2.37:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```
It has worked in the past, but since a few months or so it suddenly stopped working.
Any help would be really appreciated.

**Comment by JulianDJ01** [comment]
I fetched the plex.tv account token if that's the one you're referring to yes.

**Comment by reconman** [comment]
@JulianDJ01 Can you please repeat the token steps? Maybe your old one doesn't work anymore.

**Comment by JulianDJ01** [comment]
I've tried to fetch it in the plex media server settings from tautulli itself, but that didn't give me the same token I get from an item its .xml file. So I tried changing the config.ini file in the docker itself but it keeps on changing back to another token.

**Comment by reconman** [comment]
The config inside the container is set based on the environment variables. You have to create a new container with the correct settings.

**Comment by JulianDJ01** [comment]
Okay, I've made a new container with the updated token but now I'm getting another error.
`Tautulli Notifiers :: Script error:    Traceback (most recent call last):        File "/plexanisync/TautulliSyncHelper.py", line 7, in <module>            import coloredlogs    ModuleNotFoundError: No module named 'coloredlogs'`
I've run the install requirements.txt and even installed coloredlogs on its own.

**Comment by reconman** [comment]
Can you post your `docker run` command or `docker compose` file? Replace your tokens with placeholders.

**Comment by JulianDJ01** [comment]
```
docker run -d \
  --name=tautulli-plexanisync2 \
  -e TZ=Europe/Amsterdam \
  -e PLEX_SECTION=Anime \
  -e PLEX_URL=http://192.168.2.37:32400 \
  -e PLEX_TOKEN=[PlexToken] \
  -e ANI_USERNAME=Sm0key \
  -e ANI_TOKEN=[AnilistToken] \
  -p 8181:8181 \
  -v /app:/config \
  -v /app:/plexanisync/custom_mappings.yaml \
  --restart unless-stopped \
  ghcr.io/rickdb/tautulli-plexanisync
```

**Comment by reconman** [comment]
Can you do a `docker pull ghcr.io/rickdb/tautulli-plexanisync` and recreate the container again?

Maybe you have an old version downloaded.

**Comment by JulianDJ01** [comment]
That did it, it works great again. Thank you for your help.
