### ISSUE TITLE
Using home_username with 2FA enabled

### ISSUE THREAD

**Issue by jacobmix** [RickDB/PlexAniSync#148]
Is there any way to use home_username with 2FA enabled?
If i wanna update myself i can just use 'direct', and an X-Plex-Token
(from clicking the 3 vertical dots in the lover left corner -> get info -> View XML or going to https://plex.tv/devices.xml)
But if i wanna setup another to update for a friend. They don't get the 'View XML', but even if i get an X-Plex-Token from one of their devices.
It doesn't authorize them. If i use my token they just get synced what i watch since 'direct' doesn't use home_username.
If i use 'myplex', use my login details, and set home_username to my friend. It works. But only if 2FA is disabled.
Even if the login is added to Authorized Devices every time i start the script it still fails to authenticate.
Is there any way can also update a friend's AniList while keeping 2FA?

Error when trying to use 'myplex' with 2FA:
```
Unable to authenticate to Plex Media Server
Traceback (most recent call last):
File "/plexanisync/plexmodule.py", line 83, in authenticate
plex_account = MyPlexAccount(plex_user, plex_password)
File "/root/.local/lib/python3.10/site-packages/plexapi/myplex.py", line 91, in __init__
data, initpath = self._signin(username, password, timeout)
File "/root/.local/lib/python3.10/site-packages/plexapi/myplex.py", line 99, in _signin
data = self.query(self.SIGNIN, method=self._session.post, auth=(username, password), timeout=timeout)
File "/root/.local/lib/python3.10/site-packages/plexapi/myplex.py", line 179, in query
raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; https://plex.tv/users/sign_in.xml <?xml version="1.0" encoding="UTF-8"?> <errors>   <error>Invalid email, username, password or verification code.</error> </errors>
```
Using 'direct' but with a friend's token (They're not a home user to me or have ownership of the server. I do):
```
Unable to authenticate to Plex Media Server
Traceback (most recent call last):
File "/plexanisync/plexmodule.py", line 65, in authenticate
plex = PlexServer(base_url, token, session)
File "/root/.local/lib/python3.10/site-packages/plexapi/server.py", line 117, in __init__
data = self.query(self.key, timeout=self._timeout)
File "/root/.local/lib/python3.10/site-packages/plexapi/server.py", line 702, in query
raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; http://[REDACTED]:[REDACTED]/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```
Port, and IP redacted. But it's just the local IP, and the port i use.

**Comment by jacobmix** [comment]
You should be able to listen for specific users. Since i'm pretty sure https://github.com/phineas05/discord-rich-presence-plex let's you specify the user even when using a token.

**Comment by reconman** [comment]
I think it's easily doable by adding a myplex_token config parameter and using `plex_account = MyPlexAccount(plex_user, plex_password, plex_token)` in plexmodule.py.

I'm currently swamped with issues in another repo, so it'll take a bit to fix.
