### ISSUE TITLE
ARM?

### ISSUE THREAD

**Issue by WiseMMO** [RickDB/PlexAniSync#16]
I'm guessing the docker version isn't compatible with ARM architecture? I cannot run it on my RPi4 for obvious reasons

**Comment by RickDB** [comment]
Docker hub sadly doesn't allow for automated ARM builds easily however just build and pushed an image on RPi3 which you can install via:

docker pull rickdb/plexanisync:arm

That ran on that without errors and just let me know if that will work on RPi 4 as well :)
