### ISSUE TITLE
Docker version cannot parse title "86"

### ISSUE THREAD

**Issue by ghost** [RickDB/PlexAniSync#168]
I assume the docker container only needs to be updated since I get this error:
![image](https://user-images.githubusercontent.com/30257011/209997434-30ab5fa7-8194-4c7a-a434-a5dd034351b7.png)

I cannot find the bug in the code itself/ cannot find the line it is referring to. I.e cannot find the method `guessit`

I think docker is a very old version of this repository, at least a year old.

Everything in this repository seems good already to just deploy a new version to docker, how difficult would it be to update the docker version? If it's fine I'll try to update python to 3.11 too, seemed to work on my machine without any issues but always good to check on the proper machine I'm running this.

**Comment by nm-remarkable** [comment]
This can be deleted.
The issue is that permission to upload to docker.io have been removed but that is no longer being supported by the automatic releases of this project.
