### ISSUE TITLE
wont work on 10.8.9

### ISSUE THREAD

**Issue by birdboytoy** [RickDB/PlexAniSync#180]
plugin keeps saying malfunctioned

**Comment by KaiserBh** [comment]
Any logs?

**Comment by birdboytoy** [comment]
i can im using windows 11 i had it working on it before do u know were the logs would be

**Comment by reconman** [comment]
Which plugin are you talking about? PlexAniSync doesn't even have a version 10.8.9.

**Comment by birdboytoy** [comment]
wrong thing im so dum
