### ISSUE TITLE
PlexAniSync-1.3.22 appears to be non-functional.

### ISSUE THREAD

**Issue by Raptor2213** [RickDB/PlexAniSync#184]
I just 'upgraded' from v1.3.21 to .22.  Unfortunately, it seems to have some critical errors in the .zip variant of the release.  When I run it, here are the errors I receive: 

C:\Program Files\PlexAniSync>python PlexAniSync.py
Traceback (most recent call last):
  File "C:\Program Files\PlexAniSync\PlexAniSync.py", line 10, in <module>
    from plexanisync.anilist import Anilist
  File "C:\Program Files\PlexAniSync\plexanisync\anilist.py", line 10, in <module>
    from plexanisync.graphql import AnilistSeries, GraphQL
  File "C:\Program Files\PlexAniSync\plexanisync\graphql.py", line 9, in <module>
    from sgqlc.endpoint.requests import RequestsEndpoint
ModuleNotFoundError: No module named 'sgqlc'

**Comment by Raptor2213** [comment]
Rolled back to .21, and it's still working.

**Comment by reconman** [comment]
Run `pip install -r requirements.txt`

**Comment by Raptor2213** [comment]
Documentation for install requirements hasn’t changed.
Changelog mentions sgqlc, but it seems to not be documented anywhere else.

**Comment by reconman** [comment]
It hasn't changed because it's still the same step. Run the command and it'll work again.
