### ISSUE TITLE
Error after updating to 1.3.22

### ISSUE THREAD

**Issue by dGstone18** [RickDB/PlexAniSync#185]
Getting the following error in the logs after updating to 1.3.22 running as a docker on Unraid. 1.3.21 continues to work without issue. I've bashed into the docker shell and confirmed that the pip requirements are installed.

`Traceback (most recent call last):
  File "/plexanisync/PlexAniSync.py", line 106, in <module>
    start()
  File "/plexanisync/PlexAniSync.py", line 69, in start
    if anilist_settings.getboolean("skip_list_update", False):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 1322, in get
    return _impl(self._name, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 844, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 824, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 819, in _get
    return conv(self.get(section, option, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 1182, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: `

**Comment by reconman** [comment]
What's the value of the SKIP_LIST_UPDATE environment variable?

The code can deal with it not being set, but I think your Unraid config set it to `""`.

Try `SKIP_LIST_UPDATE=False`.

**Comment by dGstone18** [comment]
That did it. Yes, the variable was empty. Thanks for the assist!

**Comment by reconman** [comment]
I'll add some code to deal with that in the future.
