### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BlueDragon709** [RickDB/PlexAniSync#19]
I love your syncer, but i noticed today in the log that it crashed on the same place multiple times.
See this pastebin: https://pastebin.com/2ADRy4aL 
Do you know why this is?

**Comment by BlueDragon709** [comment]
I have been testing for a while now and it seems that this only happened twice. since then it hasn't happened yet.

**Comment by RickDB** [comment]
AniList had some downtime recently so that could be it as error seems to be reporting no data being returned (empty JSON array) so most likely it was unable to reach their API server.

If it happens again would check if Python.exe is blocked by any firewall.

**Comment by RickDB** [comment]
Closing for now and if it happens again feel free to reopen.
