### ISSUE TITLE
Initial D update gets skipped

### ISSUE THREAD

**Issue by user4302** [RickDB/PlexAniSync#200]
im currently watching season 4, but the update skips it saying that its marked as complete

![image](https://github.com/RickDB/PlexAniSync/assets/32593782/4c95d144-1efe-4e17-b2c6-4722835a8197)

![image](https://github.com/RickDB/PlexAniSync/assets/32593782/c45c2cb8-727e-4cc4-aab1-b09e83ea46d7)

**Comment by Soitora** [comment]
Please provide image on how your seasons are named on Plex, and also what mapper you're using

**Comment by reconman** [comment]
You'll need a custom mapping to match the seasons properly.

PlexAniSync doesn't know that Initial D seasons are named "2nd stage", "3rd stage" and so on.

**Comment by user4302** [comment]
> Please provide image on how your seasons are named on Plex, and also what mapper you're using

apologies for the very late reply

i think its named like this?
![image](https://github.com/RickDB/PlexAniSync/assets/32593782/2c3ca594-a674-4f3a-b846-c97e38b05fe2)
the title is empty for some reason, but it seems to have a name

**Comment by user4302** [comment]
> You'll need a custom mapping to match the seasons properly.
> 
> PlexAniSync doesn't know that Initial D seasons are named "2nd stage", "3rd stage" and so on.

oh.. ok
its seems to not be added here
https://raw.githubusercontent.com/RickDB/PlexAniSync-Custom-Mappings/main/series-tvdb.en.yaml

i might tale some time to add it.
if anyone else already knows how to add it correctly, please go ahead
