### ISSUE TITLE
i cant seem to match this anime movie no matter what

### ISSUE THREAD

**Issue by user4302** [RickDB/PlexAniSync#205]
the PlexAniSync.py output
![image](https://github.com/RickDB/PlexAniSync/assets/32593782/11674715-5c20-42f2-9521-7c566c29ad53)

my anilist entry at https://anilist.co/anime/10294/Towanoquon-The-Ephemeral-Petala/
![image](https://github.com/RickDB/PlexAniSync/assets/32593782/fb28834c-cea1-4436-81b8-9211bf3d342c)

my custom-mapping.yaml entry
![image](https://github.com/RickDB/PlexAniSync/assets/32593782/cfbc1655-d4fc-42a9-a474-75105a6248a0)

**Comment by reconman** [comment]
Custom mapping should have your Plex title in it. You don't need the synonyms.

Since your Plex title is different than the mapping titles, it doesn't use the mapping.

**Comment by user4302** [comment]
> Custom mapping should have your Plex title in it. You don't need the synonyms.
> 
> Since your Plex title is different than the mapping titles, it doesn't use the mapping.

so this is my plex title
![image](https://github.com/RickDB/PlexAniSync/assets/32593782/177e5178-0fc2-449c-ab06-2ef8adbbe685)

what should i do now exactly?
make the title on the custom mapping be this:
`Towa no Quon 1: The Ephemeral Petals`?

**Comment by Soitora** [comment]
Either change Plex title to match Mapper, or change mapper Title to match Plex

If I got time later before I depart, I can add the movies to the TMDB community movie mapping

**Comment by user4302** [comment]
thanks loads, safe journey to wherever youre departing to.
