### ISSUE TITLE
HTTP 500 error "bad request"

### ISSUE THREAD

**Issue by zmeizy** [RickDB/PlexAniSync#231]
Log:
[PlexAniSync.log](https://github.com/RickDB/PlexAniSync/files/13929530/PlexAniSync.log)

**Comment by reconman** [comment]
When you sort your plex titles in "Anime English" alphabetically, what comes after `Bottom-Tier Character Tomozaki`?

**Comment by zmeizy** [comment]
![Ekrānuzņēmums 2024-01-13 233241](https://github.com/RickDB/PlexAniSync/assets/73398044/bf53d2bb-7196-429b-bd0e-6557dd98e195)

**Comment by reconman** [comment]
Can you upload your `PlexAniSync-DEBUG.log`?

**Comment by zmeizy** [comment]
[PlexAniSync-DEBUG.log](https://github.com/RickDB/PlexAniSync/files/13929570/PlexAniSync-DEBUG.log)

**Comment by reconman** [comment]
Okay, the issue is with Bottom-Tier Character Tomozaki S2 but I have no idea why.

If I search manually, it returns results just fine.

Can you add a custom mapping for S2 and see if any other series is affected?

**Comment by zmeizy** [comment]
I have no idea why either but adding it fixed the problem for whatever reason lol.
Anyways, here are the log files after adding the custom mapping  if you want to take a view.
[PlexAniSync-DEBUG.log](https://github.com/RickDB/PlexAniSync/files/13929741/PlexAniSync-DEBUG.log)
[PlexAniSync.log](https://github.com/RickDB/PlexAniSync/files/13929742/PlexAniSync.log)

**Comment by reconman** [comment]
I fixed it by adding retries in PlexAniSync when this error is encountered, but hopefully Anilist fixes it on their end at some point.
