### ISSUE TITLE
Help with invalid token error

### ISSUE THREAD

**Issue by Ecleptic** [RickDB/PlexAniSync#232]
Hey there! I've the unraid docker container It's been working flawlessly for months but somewhat recently it has been failing. 

I followed the [Link](https://anilist.co/api/v2/oauth/authorize?client_id=1549&response_type=token) to get my api token and put it in the `ANI_TOKEN` container variable. It's failing with 
`{"errors":[{"message":"Invalid token","status":400,"locations":[{"line":2,"column":1}]}],"data":{"MediaListCollection":null}}`
"Unable to retrieve AniList list, check your username and access token"

I'm sure I've messed something up, but I'm not quite certain what it is.

**Comment by reconman** [comment]
So you retrieved a new token recently?

**Comment by Ecleptic** [comment]
I retrieved the token today. I checked twice. to make sure that I got the whole string and no whitespace.

**Comment by reconman** [comment]
DM me the username + token on Discord, I'll check if I can see what's wrong.

My username is reconman.

**Comment by Ecleptic** [comment]
I've sent you a friend request. I don't know how to message none friends that don't have mutual servers with.

**Comment by reconman** [comment]
Custom settings.ini was used which resulted in ANI_TOKEN being ignored

**Comment by Ecleptic** [comment]
For future reference. I had a settings.ini file as well as the docker variables. The settings.ini overwrites the docker containers so my changes weren't doing anything. 

Thank you @reconman
