### ISSUE TITLE
Possible to use with accounts w/ library access?

### ISSUE THREAD

**Issue by hotsno** [RickDB/PlexAniSync#236]
Just want to confirm it's not possible to use Plex accounts other than the admin account and Plex home accounts for this.

i.e. I can't use this for a friend who I've added via Settings > Manage Library Access.

**Comment by reconman** [comment]
I recently found out it's possible to also sync someone's progress by using direct authentication with their username and token.

The token can be found this way: https://www.plexopedia.com/plex-media-server/general/plex-token/#getcurrentusertoken

They'll have to give it to you.
