### ISSUE TITLE
Single season to multiple AniList?

### ISSUE THREAD

**Issue by mishugashu** [RickDB/PlexAniSync#26]
I use Sonarr to download shows for Plex, which uses TVDB. TVDB has decided that multiple seasons running in a row are going to be a singular season. So, for Ascendance of the Bookworm, we have 26 episodes in season 1 (https://www.thetvdb.com/series/ascendance-of-a-bookworm) instead of 2 seasons of 14 and 12 episodes on AniList (https://anilist.co/anime/108268/Ascendance-of-a-Bookworm/ and https://anilist.co/anime/113693/Ascendance-of-a-Bookworm-Part-2/) - is there a way that I can map this so the script can -for example - update "Ascendance of a Bookworm" episode 16 to be Part 2, episode 4?

**Comment by RickDB** [comment]
Not possible sadly, for that show and best solution is to split them up in seasons to follow AniList + TVDB.
Afterwards can use custom mappings to map the different seasons correctly.

TVDB sucks sometimes and hard to get changes pushed thru or some user just keeps messing with the entries for it, can always try to see if you can get it corrected by some admin there though.
Do have XREF support planned like HAMA agent uses which includes AniDB matching and will improve matching further although with shows like this no automated solution possible.

**Comment by mishugashu** [comment]
Unfortunately, this seems to be the behaviour that is wanted by the TVDB admins (https://forums.thetvdb.com/viewtopic.php?f=42&t=25066&sid=e8cb1d9ff04c868b424062c43ba1e3ca). And Sonarr only supports TVDB. And Sonarr handles the directory formats and naming as such. I guess I just have to manually deal with things like this and hope that Sonarr starts supporting other databases in the future. Or go back to my flexget scripts instead of Sonarr. Thanks for the answer.
