### ISSUE TITLE
None check needed?

### ISSUE THREAD

**Issue by Funi1234** [RickDB/PlexAniSync#27]
Just got this while running the script. I assume its because `item` was None.

` File "/mnt/data/PlexAniSync/anilist.py", line 1217, in find_id_best_match
    if item[0] is not None:
TypeError: 'NoneType' object is not subscriptable`

**Comment by RickDB** [comment]
If it was None should process the next one in the list so that's a bit odd, does it happen for the first entry or for a certain series?

**Comment by Funi1234** [comment]
I did my own quick fix shortly after creating this bug to overcome it and now I cant replicate. I also don't have the output anymore. 

I'll close the issue due to losing all the details surrounding it.
