### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by danield42** [RickDB/PlexAniSync#28]
Docker Image: rickdb/plexanisync:latest@sha256:dd4e2c83300c69165a74998781daf8af75b4e1bc8e9ba9f41e343bfe6aac3f1e

> 2020-05-25 08:59:43 [PLEX] Retrieving episode watch count for show: World Trigger | season: 2
> Traceback (most recent call last):
>   File "PlexAniSync.py", line 165, in <module>
>     start()
>   File "PlexAniSync.py", line 155, in start
>     anilist.match_to_plex(
>   File "/plexanisync/anilist.py", line 660, in match_to_plex
>     match_series_with_seasons(
>   File "/plexanisync/anilist.py", line 941, in match_series_with_seasons
>     media_id_search = find_id_season_best_match(
>   File "/plexanisync/anilist.py", line 1193, in find_id_season_best_match
>     if started_year < match_year:
> TypeError: '<' not supported between instances of 'str' and 'int'

Let me know if I can supply you with any further information. Keep up the good work :)

_Edit: formatting, "code" doesnt respect line breaks_

**Comment by RickDB** [comment]
Pushed fix and updating docker images now.
