### ISSUE TITLE
Powershell script to work around Tautulli's environment pollution (Windows)

### ISSUE THREAD

**Issue by Jessidhia** [RickDB/PlexAniSync#29]
When running PMS/Tautulli/PlexAniSync on Windows, you need to have both a Python 2 install (for Tautulli) and a Python 3 install (for, uh, everything else); unlike other OSes, both versions get installed to different folders in PATH so they both hobble the `python` command name (instead of `python2` or `python3`), nobody looks at shebangs, and if the sync helper script is invoked from Tautulli directly as a python script, it will be invoked with Python 2, which fails. Simply making it so the script gets invoked with Python 3 is not sufficient either, as Tautulli will also set PYTHONPATH, which leads to a crash.

I could have done this the easy way with a `.bat` script but I wanted an excuse to learn powershell and this seemed like a simple enough task, so here's a `.ps1` wrapper for `TautulliSyncHelper.py`:

```ps1
param(
    [Parameter(Position = 0, ValueFromRemainingArguments)]
    $Args
)

# these are set from Tautulli and cause a crash if not unset
Remove-Item Env:PYTHONPATH, Env:PYTHONHOME 2>&1 | Out-Null

C:\Python3*\python.exe TautulliSyncHelper.py $Args
```

**Comment by RickDB** [comment]
Awesome workaround for the Tautulli limitations and added to repo 👍
