### ISSUE TITLE
Error Parsing movies

### ISSUE THREAD

**Issue by icco** [RickDB/PlexAniSync#30]
```
Traceback (most recent call last):
  File "PlexAniSync.py", line 165, in <module>
    start()
  File "PlexAniSync.py", line 155, in start
    anilist.match_to_plex(
  File "/plexanisync/anilist.py", line 660, in match_to_plex
    match_series_with_seasons(
  File "/plexanisync/anilist.py", line 741, in match_series_with_seasons
    plex_watched_episode_count = plexmodule.get_watched_episodes_for_show_season(
  File "/plexanisync/plexmodule.py", line 255, in get_watched_episodes_for_show_season
    for episode in show.episodes():
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 296, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
AttributeError: 'Movie' object has no attribute 'episodes'
```

Running off of the latest x86 docker image

**Comment by RickDB** [comment]
Seems like it's parsing a movies library which is not fully supported yet, on the Plex server side is the library of type Movies and what agent is it using (Plex Movies / HAMA etc..)?

**Comment by icco** [comment]
Yup, library type is movies. I have Hana agent installed, but happens on both Plex agent and Hana agent.

**Comment by RickDB** [comment]
Thanks, will add a fix for this :)

Still have a rework planned which includes  improved OVA / ONA support just not a lot of free time at the moment.

**Comment by RickDB** [comment]
Building Docker images now and should be there in an hour or so.

**Comment by icco** [comment]
Will do!

**Comment by icco** [comment]
Also if I can do anything to help test a movie library, let me know (supply some sort of data blob for testing, help you build such a library, etc).

**Comment by RickDB** [comment]
Currently setting up a separate library with some old movies for testing so that will help :)
Did the last change fix the issue or report an error without crashing this time?

**Comment by icco** [comment]
Yup! It fixed it from crashing.
