### ISSUE TITLE
Sangatsu no Lion counting as 1 episode, not recognize season 2

### ISSUE THREAD

**Issue by COzakaki** [RickDB/PlexAniSync#32]
Hi when syncing it updates my aniilist with only 1 episode. I pushed both seasons to completed in Plex. I don't believe it's caused by the Plex Optimized Versions cause it recognizes Chihafaryu but I have not tested with S2 and S3. I was thinking it was the special in S1E11.5 so I deleted it but it didn't help. Attached are the logs, file structure in my folders, and plex dash. Maybe it's due to Sangatsu no Lion 2 considered a separate entry?

[PlexAniSync.log](https://github.com/RickDB/PlexAniSync/files/4815958/PlexAniSync.log)

![image](https://user-images.githubusercontent.com/52932929/85343327-92eace80-b4ba-11ea-8c39-8e30ecacbc39.png)
![image](https://user-images.githubusercontent.com/52932929/85343359-a8f88f00-b4ba-11ea-810e-1710ba351d0e.png)

**Comment by MrDemocracy** [comment]
Have you tried using custom mappings as a workaround?
Add this to `custom_mappings.ini.example` and remove .example from its filename:
‎‎‎‎‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎↓
```
Sangatsu no Lion^1^21366
Sangatsu no Lion^2^98478
```

**Comment by COzakaki** [comment]
Mapping works! Thank you so much!
