### ISSUE TITLE
Tautulli script error | Manjaro 20

### ISSUE THREAD

**Issue by LetrixZ** [RickDB/PlexAniSync#34]
Running "python PlexAniSync.py" via terminal doesn't cause any problems but when running the automated script I get this error in Tautulli logs and so the script isn't executed. All requirements are installed.

`Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/home/fermin/PlexAniSync/TautulliSyncHelper.py", line 7, in <module>
            import coloredlogs
    ModuleNotFoundError: No module named 'coloredlogs'`

I installed Plex and Tautulli via AUR packages. 

Full logs: [tautulli.log](https://github.com/RickDB/PlexAniSync/files/5005481/tautulli.log)

**Comment by KaiserBh** [comment]
you are missing a module, did you install the requierements.txt? 

try running inside the folder.
`Run pip install -r requirements.txt (Python 2), or pip3 install -r requirements.txt (Python 3)`
or just install the coloredlogs 
https://pypi.org/project/coloredlogs/

which is 
`pip install coloredlogs`

**Comment by LetrixZ** [comment]
As I said before, all requirements are installed, that's why the main script "PlexAniSync.py" is excuted correctly when run on terminal, but "TautulliSyncHelper.py" is not when run on the automated script.

**Comment by 46620** [comment]
Make sure that colorlogs is installed with what version of python Tautulli is using. I had the same issue and it was because tautulli was using python2 not python3.

**Comment by LetrixZ** [comment]
Reinstalled Tautulli via official Linux method. I have these pip versions: pip, pip2, pip2.7, pip3, pip3.8. All those have the requirements installed but still giving the same error. Tautulli is running on Python 3.

**Comment by RickDB** [comment]
Tautulli can be weird on how it runs its scripts as I've seen this before with other users with mixed Python installs.

Can you check which binary is used by Tautulli itself and also Tautulli had a few fixes recently for script execution so can't hurt to update :)

**Comment by LetrixZ** [comment]
Updated Tautilli, reinstalled script but still getting the same error.

**Comment by LetrixZ** [comment]
Fixed it by installing the requirement as a super user under Arch Linux.
`sudo pip install -r requirements.txt`
