### ISSUE TITLE
Serie with mapping status and 100% completed is "Watching 1/XX"

### ISSUE THREAD

**Issue by Tawagot0** [RickDB/PlexAniSync#36]
Hi! Thanks for the project, have an issue about the status of two animes with custom_mapping.
I have a synchronization problem when an anime is watched at 100% (so it's finished), except that it puts each time there is only one episode seen over the whole season.

```
Ace of Diamond^1^18689
Ace of Diamond^2^21085
Ace of Diamond^3^105749
Gambling School^1^98314
Gambling School^2^100876
``` 

Logs:

```
2020-08-28 17:28:22 [MAPPING] Adding custom mapping | title: Gambling School | season: 1 | anilist id: 98314
2020-08-28 17:28:22 [MAPPING] Adding custom mapping | title: Gambling School | season: 2 | anilist id: 100876
2020-08-28 17:29:11 Found multiple seasons so using season search instead for: Gambling School
2020-08-28 17:29:11 [PLEX] Retrieving episode watch count for show: Gambling School | season: 1
2020-08-28 17:29:11 [PLEX] Show appears to be movie (no episodes attribute) and trying fallback approach to determine watched state
2020-08-28 17:29:11 [PLEX] Retrieving episode watch count for show: Gambling School | season: 1
2020-08-28 17:29:11 [PLEX] Show appears to be movie (no episodes attribute) and trying fallback approach to determine watched state
2020-08-28 17:29:11 [ANILIST] Used custom mapping id 98314  |  title: Gambling School | season: 2 | anilist id: 98314
2020-08-28 17:29:11 [ANILIST] Updating series id to list: 98314 | Plex episodes watched: 1
2020-08-28 17:29:11 [ANILIST] Found AniList entry for Plex title: Gambling School
2020-08-28 17:29:11 [ANILIST] Series year did not match however skip year check was given so adding anyway => Plex has 1970 and AniList has 2017
2020-08-28 17:29:11 [ANILIST] Episodes watched was the same on AniList and Plex so skipping update
```

I don't know why he said Plex has year 1970 (i think it's default with no meta) : https://github.com/RickDB/PlexAniSync/blob/d71fb10bf31d3e27c69d075c048bd37d83a18245/anilist.py#L1114
I use TheTVDB, but only when i leave an episode as unseen, the script works very well so for example for Gambling School Season 1 with the script it's 11/12.

More information:
- Docker (https://github.com/RickDB/Docker-PlexAniSync)
- Branch: Master
- TheTVDB

**Comment by KaiserBh** [comment]
Have you got the full logs? 
There should be log containing debug and normal log that write to the file system.

Also can you please elaborate more on what's the issue? 
Are you saying shows that you put in custom mapping shows as watching 1/XX in AniList?

**Comment by Tawagot0** [comment]
Sorry @KaiserBh i misspoke, I didn't even describe the problem I had when I gave the information lol.
I have a synchronization problem when an anime is watched at 100% (so it's finished), except that it puts each time there is only one episode seen over the whole season.
Full logs: https://pastebin.com/J1rDpyuL

**Comment by KaiserBh** [comment]
Do you have movie called gambling school by any chance? 

Also can you do me a favour try marking 11 episode as watched, and the last one unwatched for gambling school.

And then run the sync again.

**Comment by Tawagot0** [comment]
No movie with that name (moreover it does it to me for several series), not exactly how I launch the script being 11/12 on Plex on AniList it puts me 11/12 but when I relaunch the script being in 12/12, on AniList it goes back to 1/12.
I would like to specify that I tried to do it without container docker and by changing the authentication method I have the same problem.

**Comment by KaiserBh** [comment]
> No movie with that name (moreover it does it to me for several series), not exactly how I launch the script being 11/12 on Plex on AniList it puts me 11/12 but when I relaunch the script being in 12/12, on AniList it goes back to 1/12.
> I would like to specify that I tried to do it without container docker and by changing the authentication method I have the same problem.

Okay guessing there is some issue with the script then, I will try to have a look sometime next week if I am free will try to fix it, do you have the DEBUG log by anychance that you can attach here?

**Comment by Tawagot0** [comment]
I don't have a debug log unfortunately, however I continued my tests and found something interesting.

**First step:**
Delete all series with the problem on AniList.
I would like to specify that for this test all series have been completed.
We can see that all the seasons of the series with a custom mapping are in 1/XX.
![image](https://user-images.githubusercontent.com/26726263/91636286-ad33b200-e9ff-11ea-973e-fed23ab888cd.png)


**2nd step:**
Delete again all series on AniList and mark an unseen episode on a season of a series only.

Plex Serie:
![image](https://user-images.githubusercontent.com/26726263/91636326-ed933000-e9ff-11ea-9c6d-f704f95fd7c5.png)

And now on AniList:
![image](https://user-images.githubusercontent.com/26726263/91636406-87f37380-ea00-11ea-92a9-11c86e91ce24.png)
This is the perfect behavior for Ace of Diamond because it's missing an episode and it's still "Watching" but the other seasons are marked as "Completed".

**Comment by KaiserBh** [comment]
> I don't have a debug log unfortunately, however I continued my tests and found something interesting.
> 
> **First step:**
> Delete all series with the problem on AniList.
> I would like to specify that for this test all series (and all seasons of the serie) have been completed.
> We can see that all the seasons of the series with a custom mapping are in 1/XX.
> ![image](https://user-images.githubusercontent.com/26726263/91636286-ad33b200-e9ff-11ea-973e-fed23ab888cd.png)
> 
> 
> **2nd step:**
> Delete again all series on AniList and mark an unseen episode on a season of a series only.
> 
> Plex Serie:
> ![image](https://user-images.githubusercontent.com/26726263/91636326-ed933000-e9ff-11ea-9c6d-f704f95fd7c5.png)
> 
> And now on AniList:
> ![image](https://user-images.githubusercontent.com/26726263/91636406-87f37380-ea00-11ea-92a9-11c86e91ce24.png)
> This is the perfect behavior for Ace of Diamond because it's missing an episode and it's still "Watching" and the other seasons are marked as "Completed".
> 

Are you using the latest docker and PlexAniSync? Because in the latest one there should be debug log and standard log that writes into text file?

**Comment by Tawagot0** [comment]
> 
> 
> > I don't have a debug log unfortunately, however I continued my tests and found something interesting.
> > **First step:**
> > Delete all series with the problem on AniList.
> > I would like to specify that for this test all series (and all seasons of the serie) have been completed.
> > We can see that all the seasons of the series with a custom mapping are in 1/XX.
> > ![image](https://user-images.githubusercontent.com/26726263/91636286-ad33b200-e9ff-11ea-973e-fed23ab888cd.png)
> > **2nd step:**
> > Delete again all series on AniList and mark an unseen episode on a season of a series only.
> > Plex Serie:
> > ![image](https://user-images.githubusercontent.com/26726263/91636326-ed933000-e9ff-11ea-9c6d-f704f95fd7c5.png)
> > And now on AniList:
> > ![image](https://user-images.githubusercontent.com/26726263/91636406-87f37380-ea00-11ea-92a9-11c86e91ce24.png)
> > This is the perfect behavior for Ace of Diamond because it's missing an episode and it's still "Watching" and the other seasons are marked as "Completed".
> 
> Are you using the latest docker and PlexAniSync? Because in the latest one there should be debug log and standard log that writes into text file?

For this test latest PlexAniSync manual. I can try with docker if you want?

**Comment by KaiserBh** [comment]
uhh, the debug file is empty?? I will have a look at it if you want you can test it out but it won't make any difference since the docker version is using this version.

**Comment by Tawagot0** [comment]
> 
> 
> uhh, the debug file is empty?? I will have a look at it if you want you can test it out but it won't make any difference since the docker version is using this version.

Have logs with docker!
Is it possible to send these logs privately (by email or Discord) in case there is sensitive information.
My Discord: Tawagoto#0001

**Comment by KaiserBh** [comment]
> > uhh, the debug file is empty?? I will have a look at it if you want you can test it out but it won't make any difference since the docker version is using this version.
> 
> Have debug logs with docker!
> Is it possible to send these logs privately (by email or Discord) in case there is sensitive information.
> My Discord: Tawagoto#0001

it's all good, I tested it myself and can confirm that's it is an issue. I managed to get the same result as yours. But I believe the culprit is most likely in this function

```python
def get_watched_shows(shows):
    logger.info("[PLEX] Retrieving watch count for series")
    watched_series = []
    ovas_found = 0

    for show in shows:
        season_total = 1
        season_watched = 1
        episodes_watched = 0

        if hasattr(show, "episodes"):
            for episode in show.episodes():
                try:
                    # If season not defined set to season 1
                    season = 1 if not episode.seasonNumber else episode.seasonNumber
                    n_episode = episode.index
                    if episode.isWatched and n_episode:
                        if (
                            n_episode > episodes_watched and season == season_watched
                        ) or (season > season_watched):
                            season_watched = season
                            episodes_watched = n_episode
                            season_total = season
                        else:
                            episodes_watched = 0
                except Exception as e:
                    logger.error(
                        "Error during lookup_result processing, traceback: %s" % (e)
                    )
                    pass
            if episodes_watched > 0:
                # Add year if we have one otherwise fallback
                year = 1900
                if show.year:
                    year = show.year

                if not hasattr(show, "titleSort"):
                    show.titleSort = show.title
                elif show.titleSort == "":
                    show.titleSort = show.title

                # Disable original title for now, results in false positives for yet unknown reason

                # if not hasattr(show, 'originalTitle'):
                #    show.originalTitle = show.title
                # elif show.originalTitle == '':
                #    show.originalTitle = show.title
                show.originalTitle = show.title

                watched_show = plex_watched_series(
                    show.title.strip(),
                    show.titleSort.strip(),
                    show.originalTitle.strip(),
                    year,
                    episodes_watched,
                    season_total,
                )
                watched_series.append(watched_show)

                # logger.info(
                #    'Watched %s episodes of show: %s' % (
                #        episodes_watched, show.title))
        else:
            # Probably OVA but adding as series with 1 episode and season
            # Needs proper solution later on and requires changing AniList
            # class to support it properly

            if hasattr(show, "isWatched"):
                if show.isWatched:
                    year = 1900
                    if show.year:
                        year = show.year

                    if not hasattr(show, "titleSort"):
                        show.titleSort = show.title
                    elif show.titleSort == "":
                        show.titleSort = show.title

                    # Disable original title for now, results in false positives for yet unknown reason

                    # if not hasattr(show, 'originalTitle'):
                    #    show.originalTitle = show.title
                    # elif show.originalTitle == '':
                    #    show.originalTitle = show.title
                    show.originalTitle = show.title

                    watched_show = plex_watched_series(
                        show.title.strip(),
                        show.titleSort.strip(),
                        show.originalTitle.strip(),
                        show.year,
                        1,
                        1,
                    )
                    watched_series.append(watched_show)
                    ovas_found += 1

    logger.info("[PLEX] Found %s watched series" % (len(watched_series)))

    if ovas_found > 0:
        logger.info(
            "[PLEX] Watched series also contained %s releases with no episode attribute (probably movie / OVA), support for this is still experimental"
            % (ovas_found)
        )

    if watched_series is not None and len(watched_series) == 0:
        return None
    else:
        return watched_series
```
See how it already calculated the watch count as 1 so if you mark a show as watch immediately without watching any episodes it will assume you watched the first episode only, so a solution that I come up with is that check if the season is watched or marked as watched if the season is marked as watch there is no need to get the watched episodes individually instead just get the episode count total then pass it that way it updates everything  Plexapi have a method for that but I haven't used it much or know how the attribute works etc, I will give it a try and fix it but at best is just wait for @RickDB which he will be busy I believe probably until next week or so.

**Comment by reconman** [comment]
Can you check whether it still happens after my bug fixes?

**Comment by KaiserBh** [comment]
> 
> 
> Can you check whether it still happens after my bug fixes?

Just tested it, seem to be working well with Kakegurui thanks for this 👍
