### ISSUE TITLE
Request: Could we get more than 1 library?

### ISSUE THREAD

**Issue by ay3w** [RickDB/PlexAniSync#4]
I have anime movies and tv shows separated into two libraries (because TMDB is a better agent and source than HAMA for movies usually and because the UI is better suited if you categorise as a movie).
So at the moment I can't sync my movies automatically.

**Comment by RickDB** [comment]
Sure, will add later this week 👍

**Comment by RickDB** [comment]
For HAMA Movies support it's gonna get tricky as that does not have an episode count in Plex, I could fallback to 1 which should work but needs more testing.

**Comment by RickDB** [comment]
Tested the multiple library part but let me know if you have any issues with movies / ova's as I lack the library type on my PMS for that at the moment.

**Comment by ay3w** [comment]
PlexAniSync.py returns this:
[PLEX] Watched series also contained 17 releases with no episode attribute (probably movie / OVA), support for this is still experimental 

There are 84 items in the library that have matches on AniList so it only seems to be doing it for some.

[full console printout](https://github.com/RickDB/PlexAniSync/files/3251987/plexanisyncprintout_040619.txt)

Thanks for implementing.

As a side note, apparently you can have trailing spaces in the names for Plex libraries, which threw me errors until I though to check that.

**Comment by RickDB** [comment]
Good to hear, would have expected Plex to trim the names but will add that now :)

**Comment by RickDB** [comment]
Validation added for library / section names and trim added in a few places.

If you can post the AniList ID's / links for the movies with the Plex entry info (title / year) that aren't matching will take a further look, while it wasn't designed with movies in mind would be nice if we can add support for it at least.

**Comment by RickDB** [comment]
Closing this for now, for any issues with Movie matching would open a new issue and will take a look.
