### ISSUE TITLE
Secure connection "Required" on server breaks handshake

### ISSUE THREAD

**Issue by wally503** [RickDB/PlexAniSync#41]
I have a user who requires secure handshakes on their ISP. Plex unfortunately doesn't manage handshakes to https for them correctly, so I set my settings in plex to required in the following area:

Server Name > Settings > Network >>>> **Secure Connections: Preferred -> Required**

When I do that, I get timeouts from the application trying to handshake. You would think that changing the url on the base_url to HTTPS would alleviate it, but it still will not connect.

> Unable to authenticate to Plex Media Server, traceback: HTTPSConnectionPool(host='192.168.1.15', port=32400): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname '192.168.1.15' doesn't match '*.fd1951fbfe2247368d9a9b68577edf77.plex.direct'")))
> Plex authentication failed, check access to your Plex Media Server and settings
> 

I currently have the following settings
**base_url = https://192.168.1.15:32400**
where if I change the settings back to preferred, changing back to http from https will make anisync work again. 

I can't think of other means to try out the https connection, so I'm at a loss what to look at.

**Comment by RickDB** [comment]
Looks like this issue with the PlexAPI which PlexAniSync relies on:

https://github.com/pkkid/python-plexapi/issues/143

Added mentioned workaround there and could you test with below plexmodule.py file:

https://gist.github.com/RickDB/b61319f66ddfcf71e837bc3dbf1929c7

**Comment by RickDB** [comment]
Closing for now due to lack of response.

@wally503 if above workaround solves it for you just let me know and will make it an optional setting.

**Comment by wally503** [comment]
Just wanted to follow up on this. It does work! I am getting heavy warnings for insecure/certificate handshakes, but it does bypass the handshake limit and pushes a ton of warnings on each call to the local plex:

> C:\Users\wally\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.15'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
> 
Despite a ton of these, one every time per call to plex, it works. It appears there are just warnings in regards to what looks to be certifications, maybe on a local level? I don't know if it will cause issues in the future in terms of logs, especially on docker containers. 

I will also note http doesn't work, as it should not with the required. The following were my results for reference:

http + preferred = no warnings
http + required = fails (intended)
https + preferred = no warnings
https + required = lots of warnings

Thanks!

**Comment by RickDB** [comment]
Great :)
Added new option to suppress warnings and could you test it out:

https://gist.github.com/RickDB/b61319f66ddfcf71e837bc3dbf1929c7

**Comment by wally503** [comment]
All test cases work as intended, no warnings. Only other thing I might suggest is somewhere where documentation mentions this scenario, the current error on http + preferred, which should fail, and does, is:

> 2020-11-23 02:49:49 [ANILIST] Found 1116 anime series on list
> 2020-11-23 02:49:49 Unable to authenticate to Plex Media Server, traceback: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 2020-11-23 02:49:49 Plex authentication failed, check access to your Plex Media Server and settings
> 2020-11-23 02:49:49 Found no Plex shows for processing
> 2020-11-23 02:49:49 Found no watched shows on Plex for processing
> 2020-11-23 02:49:49 Plex to AniList sync finished

Other than that, I think it's working with no issues/warnings with local https now. 

Thank you!

**Comment by RickDB** [comment]
Awesome, will make some this weekend and update code + docker image for the new SSL setting 👍

**Comment by wally503** [comment]
> Awesome, will make some this weekend and update code + docker image for the new SSL setting 👍
> 
> Think HTTP is failing because it's expecting HTTPS with these changes but not completely sure yet.

Just wanted to update you and say I had wrote "HTTP + Preferred" by mistake when I replied that it worked. I mean to say that "HTTP + Required" should fail, not preferred. 

ONLY "HTTP + Required" should (and does) fail, as locally connecting to the box, (and probably remotely through any client) would require HTTPS on Required Secure Connection. My apologies for that. The error I supplied above that I suggested for documenting was for HTTP + Required, not Preferred.

**Comment by RickDB** [comment]
Will merge this new setting in this week so it can skip SSL validation

**Comment by reconman** [comment]
The guys over at plexapi provided an akward solution. I've found a much better one. Will commit and release the code soon.

**Comment by reconman** [comment]
I've released v1.3.6, try it out.
