### ISSUE TITLE
Native support for AniList metadata provider

### ISSUE THREAD

**Issue by sachaw** [RickDB/PlexAniSync#42]
I am the author of https://github.com/sachaw/anilist.bundle which allows for a strict naming convention and includes the AniList id, as such it should be easy to detect and support, if you could take a look, it would be much appreciated

**Comment by RickDB** [comment]
Hi,

Thanks for this, currently my time for coding is very limited but once I can resume will take a look :)

**Comment by reconman** [comment]
So, I prepared a library but can't see any show, season, or episode attributes we could use.

So where is the anilist-id stored?

**Comment by sachaw** [comment]
You will need to select your files naming convention under the library settings

**Comment by reconman** [comment]
I already did that before you commented. It loaded some metadata. And now?

**Comment by sachaw** [comment]
you can find it at the `Metadata.guid` property of any library item, take a look here for where I used it:
https://github.com/sachaw/scrobble-moe/blob/ca3719218805bde75d393d2e3aacf70462dcb0d7/app/api/webhook.ts#L31-L33

**Comment by sachaw** [comment]
Gonna take a whild guess and say you'd have to do something similar to what I posted above here: https://github.com/RickDB/PlexAniSync/blob/7d58c2d71d42c2f048dbc656a10f7bc6604d754e/anilist.py#L105-L106

**Comment by reconman** [comment]
Okay, found the attribute, but it's part of the `plexapi` library objects, you linked to the Anilist graphql transformation instead.

Before I do anything: What benefit does using the GUID have over searching by name? Since the name is pulled from anilist when using your provider, the names (and years) match perfectly and plexanisync should be able to find the show.

**Comment by sachaw** [comment]
The way anilist handles searching by name is flawed and does not allow direct matches. It also does not handle lots of different special characters. So using the I'd instead ensures that the match is correct

**Comment by RickDB** [comment]
Direct matching bij name was indeed hit and miss here as well, one of the reasons why I remove all special characters when comparing to Plex at the moment.

**Comment by sachaw** [comment]
That works for the most part, but for series where the second season or related show is only differentiated by a special character becomes an issue. Luckily if you support my metadata provider, the Id is directly accessable

**Comment by RickDB** [comment]
Currently doing an library import with the Anilist bundle and if @reconman is up for it will let him handle the integration :)

**Comment by reconman** [comment]
Just to make sure, can there ever be 2 seasons in one show?

**Comment by reconman** [comment]
Assuming not, the changes introduced in 3d77958 should be able to handle all shows.

**Comment by sachaw** [comment]
Nope, completely flat libraries only, just as it in on anilist

**Comment by reconman** [comment]
@sachaw Can you test the changes? Do you need the docker images?

**Comment by sachaw** [comment]
Idk, I'll test it out tonight
