### ISSUE TITLE
Tautulli wiki rewording

### ISSUE THREAD

**Issue by Soitora** [RickDB/PlexAniSync#45]
👋🏻 

Tautulli has renamed their "Allow Consecutive Notifications" setting.

Relevant commit: https://github.com/Tautulli/Tautulli/commit/199119cafbea37c1bf4a0735ed437ffd949be8f6
Image: 
![image](https://user-images.githubusercontent.com/10836780/106407761-27e47b80-643d-11eb-8fb5-00dd50921331.png)

**Also**, maybe add to the Conditonals to add their Username as a requirement for the watch so it doesn't trigger on every user watching

**Comment by RickDB** [comment]
Wiki updated, thanks for reporting 👍
