### ISSUE TITLE
Tautulli helper headless Python

### ISSUE THREAD

**Issue by Soitora** [RickDB/PlexAniSync#46]
👋🏻 

Currently PlexAniSync is shipped with a `TautulliSyncHelper.py` and that is the file the Tautulli guide is referring too. This should either be changed to `.pyw` or have a `.pyw` copy included with it so it doesn't make a pop-up each time.

Guide could also alternative potentially mention that it's possible to copy the file manually and change to `.pyw` and it'll work headless (except you need to redo each commit that modifies the file)

**Comment by RickDB** [comment]
Instructions updated to include headless python option, makes it easier for update purposes and still gives user the option to do run it that way :)
