### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by reconman** [RickDB/PlexAniSync#48]
Reported by allquiet-hub at https://github.com/RickDB/Docker-PlexAniSync/issues/11

Hello, sometimes on my instance i get this error, so it stops the current update, and restarts at the next time set by the interval.
> plexanisync    | 2021-02-02 00:16:21 Found multiple seasons so using season search instead for: The Irregular at Magic High School
plexanisync    | 2021-02-02 00:16:21 [PLEX] Retrieving episode watch count for show: The Irregular at Magic High School | season: 1
plexanisync    | 2021-02-02 00:16:21 [PLEX] 26 episodes watched for season 1
plexanisync    | 2021-02-02 00:16:21 [PLEX] Retrieving episode watch count for show: The Irregular at Magic High School | season: 2
plexanisync    | 2021-02-02 00:16:21 [PLEX] 13 episodes watched for season 2
plexanisync    | Traceback (most recent call last):
plexanisync    |   File "/plexanisync/PlexAniSync.py", line 168, in <module>
plexanisync    |     start()
plexanisync    |   File "/plexanisync/PlexAniSync.py", line 159, in start
plexanisync    |     anilist.match_to_plex(
plexanisync    |   File "/plexanisync/anilist.py", line 576, in match_to_plex
plexanisync    |     match_series_with_seasons(
plexanisync    |   File "/plexanisync/anilist.py", line 898, in match_series_with_seasons
plexanisync    |     media_id_search = find_id_season_best_match(
plexanisync    |   File "/plexanisync/anilist.py", line 1167, in find_id_season_best_match
plexanisync    |     if item[0].media:
plexanisync    | TypeError: 'NoneType' object is not subscriptable

Every time it's a different series. So let me put some others:

> plexanisync    | 2021-02-02 00:16:21 Found multiple seasons so using season search instead for: The Irregular at Magic High School
plexanisync    | 2021-02-02 00:16:21 [PLEX] Retrieving episode watch count for show: The Irregular at Magic High School | season: 1
plexanisync    | 2021-02-02 00:16:21 [PLEX] 26 episodes watched for season 1
plexanisync    | 2021-02-02 00:16:21 [PLEX] Retrieving episode watch count for show: The Irregular at Magic High School | season: 2
plexanisync    | 2021-02-02 00:16:21 [PLEX] 13 episodes watched for season 2
plexanisync    | Traceback (most recent call last):
plexanisync    |   File "/plexanisync/PlexAniSync.py", line 168, in <module>
plexanisync    |     start()
plexanisync    |   File "/plexanisync/PlexAniSync.py", line 159, in start
plexanisync    |     anilist.match_to_plex(
plexanisync    |   File "/plexanisync/anilist.py", line 576, in match_to_plex
plexanisync    |     match_series_with_seasons(
plexanisync    |   File "/plexanisync/anilist.py", line 898, in match_series_with_seasons
plexanisync    |     media_id_search = find_id_season_best_match(
plexanisync    |   File "/plexanisync/anilist.py", line 1167, in find_id_season_best_match
plexanisync    |     if item[0].media:
plexanisync    | TypeError: 'NoneType' object is not subscriptable`

> plexanisync    | 2021-02-02 00:19:02 [PLEX] Retrieving episode watch count for show: Ace of the Diamond | season: 2
plexanisync    | 2021-02-02 00:19:02 [PLEX] 29 episodes watched for season 2
plexanisync    | Traceback (most recent call last):
plexanisync    |   File "/plexanisync/PlexAniSync.py", line 168, in <module>
plexanisync    |     start()
plexanisync    |   File "/plexanisync/PlexAniSync.py", line 159, in start
plexanisync    |     anilist.match_to_plex(
plexanisync    |   File "/plexanisync/anilist.py", line 576, in match_to_plex
plexanisync    |     match_series_with_seasons(
plexanisync    |   File "/plexanisync/anilist.py", line 898, in match_series_with_seasons
plexanisync    |     media_id_search = find_id_season_best_match(
plexanisync    |   File "/plexanisync/anilist.py", line 1167, in find_id_season_best_match
plexanisync    |     if item[0].media:
plexanisync    | TypeError: 'NoneType' object is not subscriptable

**Comment by reconman** [comment]
https://github.com/RickDB/PlexAniSync/blob/d3fb90a2ca3d782afed6e7ab81479967d49b73c1/anilist.py#L1234 checks for None but still it tries to call `.media`?

It's definitely not related to my recent changes as I didn't touch this part of the code.

@RickDB Any idea why? I'm a python noob and checking for None should be enough to prevent this error according to the internet.

**Comment by RickDB** [comment]
Yeah none checks were added early on to prevent this as Plex metadata can be unpredictable at times (different agents / old migrated databases etc..)
