### ISSUE TITLE
[Error] SSL Wrong Version

### ISSUE THREAD

**Issue by Soitora** [RickDB/PlexAniSync#51]
I was gonna update a single show and this occured for the first time ever:

```py
2021-02-09 03:02:27 Updating single show: My Little Monster
2021-02-09 03:02:32 [ANILIST] Retrieving AniList list for user: Soitora
--- Logging error ---
Traceback (most recent call last):
  File "D:\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\Python\Python39\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Python\Python39\lib\site-packages\urllib3\connection.py", line 496, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='graphql.anilist.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\anilist.py", line 67, in process_user_list
    list_items = fetch_user_list(username)
  File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\graphql.py", line 134, in fetch_user_list
    response = send_graphql_request(query, variables)
  File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\graphql.py", line 164, in send_graphql_request
    response = requests.post(
  File "D:\Python\Python39\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\Python39\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='graphql.anilist.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python39\lib\logging\__init__.py", line 1079, in emit
    msg = self.format(record)
  File "D:\Python\Python39\lib\logging\__init__.py", line 923, in format
    return fmt.format(record)
  File "D:\Python\Python39\lib\site-packages\coloredlogs\__init__.py", line 1137, in format
    return logging.Formatter.format(self, record)
  File "D:\Python\Python39\lib\logging\__init__.py", line 659, in format
    record.message = record.getMessage()
  File "D:\Python\Python39\lib\logging\__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\TautulliSyncHelper.py", line 111, in <module>
    start()
  File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\TautulliSyncHelper.py", line 82, in start
    anilist_series = anilist.process_user_list(anilist_username)
  File "C:\Users\Simon\Code\GitHub\RickDB\PlexAniSync\anilist.py", line 82, in process_user_list
    logger.critical(f"[ANILIST] Failed to return list for user: {username}", exception)
Message: '[ANILIST] Failed to return list for user: Soitora'
Arguments: (SSLError(MaxRetryError("HTTPSConnectionPool(host='graphql.anilist.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))")),)
2021-02-09 03:03:32 Unable to retrieve AniList list, check your username and access token
```

**Comment by reconman** [comment]
Which version are you using?

**Comment by Soitora** [comment]
Of PlexAniSync I was using the latest available at the time with git

Is Docker necessary for `tautulli-plexanisync`? Never set it up on Windows before

**Comment by reconman** [comment]
Your version is from 3 days ago, the line numbers don't match up. So it's not 100 % not related to my recent work on the Plex SSL validation in 243ca57cac98fc6ca64d188c708a49da3cb84ad7.

I guess it was a hiccup on the Anilist website. Are you able to reproduce it by running TautulliSyncHelper manually?

Regarding `tautulli-plexanisync`, yeah it's based on the Docker image of Tautulli, but I saw too late that you've installed Tautulli via the Windows installer. I was forced to create the docker image because Tautulli can't run on NAS operating systems, such as Synology DSM.

**Comment by Soitora** [comment]
![image](https://user-images.githubusercontent.com/10836780/107401465-31d44180-6b03-11eb-899e-89b1c448ddb8.png)
I am running on the latest, and this was me running `TautulliSyncHelper.py` manually

**Comment by reconman** [comment]
Your command should be `git pull && copy ...`, `git merge` on its own doesn't do anything, I think.

**Comment by Soitora** [comment]
Yeah it doesn't do anything unless I'm on a fork, but just put it there for good measure since my usual command is `git fetch upstream && git merge upstream/master`

**Comment by reconman** [comment]
You still haven't clarified: this was an one time error, right?

If that's so, there's really nothing we can do about it.

**Comment by KaiserBh** [comment]
Yea it there  nothing we can do about it cause the error is pointing to the ssl version anilist using probably some hiccup on anilist server, nor your recent changes I tested it to try to reproduce the error doesn't seem to work for me. Meaning that it's working well and I can't get the errors.  

but then again if  Soitora clarify if this keep happening would be great.

**Comment by Soitora** [comment]
> You still haven't clarified: this was an one time error, right?

My bad, this is happening each try, it doesn't work at all anymore

I tried installing newest binaries for OpenSSL, didn't do anything to help.
This *started happening* after yesterdays Windows update, so maybe that changed something?

When I try Python 3.7 instead of 3.9, I begin with installing requirements, but I'm greeted with this:

```py
❯ D:\Python\Python37\python.exe -m pip install -r .\requirements.txt
Requirement already satisfied: babelfish>=0.5.5 in d:\python\python37\lib\site-packages (from -r .\requirements.txt (line 1)) (0.5.5)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out'))': /simple/beautifulsoup4/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out'))': /simple/beautifulsoup4/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out'))': /simple/beautifulsoup4/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out'))': /simple/beautifulsoup4/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out'))': /simple/beautifulsoup4/
ERROR: Could not find a version that satisfies the requirement beautifulsoup4>=4.9.3
ERROR: No matching distribution found for beautifulsoup4>=4.9.3
```

Super odd but this basically confirms the error is not a PlexAniSync issue, so I'm trying my best to solve it 😞

**Comment by KaiserBh** [comment]
> > You still haven't clarified: this was an one time error, right?
> 
> My bad, this is happening each try, it doesn't work at all anymore
> 
> I tried installing newest binaries for OpenSSL, didn't do anything to help.
> This _started happening_ after yesterdays Windows update, so maybe that changed something?
> 
> When I try Python 3.7 instead of 3.9, I begin with installing requirements, but I'm greeted with this:
> 
> ```python
> ❯ D:\Python\Python37\python.exe -m pip install -r .\requirements.txt
> Requirement already satisfied: babelfish>=0.5.5 in d:\python\python37\lib\site-packages (from -r .\requirements.txt (line 1)) (0.5.5)
> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out'))': /simple/beautifulsoup4/
> WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out'))': /simple/beautifulsoup4/
> WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out'))': /simple/beautifulsoup4/
> WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out'))': /simple/beautifulsoup4/
> WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1059: The handshake operation timed out'))': /simple/beautifulsoup4/
> ERROR: Could not find a version that satisfies the requirement beautifulsoup4>=4.9.3
> ERROR: No matching distribution found for beautifulsoup4>=4.9.3
> ```
> 
> Super odd but this basically confirms the error is not a PlexAniSync issue, so I'm trying my best to solve it 😞
> 
> **EDIT:** Super confused, did something that shouldn't fix it but it now works 🤔 Maybe having Fiddler monitoring traffic made it not work?

definitely something was blocking the network. I was going to recommend you to use vpn or some sort to just make sure it wasn't your internet. but if you got it fixed then that's good.

**Comment by Soitora** [comment]
> definitely something was blocking the network. I was going to recommend you to use vpn or some sort to make sure it wasn't your internet. but if you got it fixed then that's good.

I'm gonna try with and without Fiddler and see if the monitoring is what broke it. I wanted to figure out how many calls PlexAniSync did because I can't fix my constant rate limit on AniList. I've had to resort to mail them since no one is able to figure it out

**Comment by reconman** [comment]
Check out https://www.telerik.com/blogs/fiddler-and-modern-tls-versions

Seems like fiddler is messing with the TLS versions. Anilist still supports TLS 1.0 and 1.1 according to https://www.cdn77.com/tls-test, though.

**Comment by reconman** [comment]
While trying to check the TLS versions of anilist.co via openssl myself, I also got the same error as you did regarding `wrong version`.

When I launch openssl on my Synology NAS, I get the error, on windows I don't. Seems like something is also messing with my connections. But strangely the python library inside the docker container has no problems at all.

**Comment by reconman** [comment]
Something I found while looking for the error online is that people misconfigured the URL of the proxy and set it to **https:**//proxy:8080 instead of **http:**//proxy:8080 and got the error because of that.

I assume you had to configure fiddler as proxy somewhere on your system.

**Comment by Soitora** [comment]
I had enabled HTTPS snooping on Fiddler, which might be the issue since it I guess intercepts my traffic?

**Comment by KaiserBh** [comment]
> I had enabled HTTPS snooping on Fiddler, which might be the issue since it I guess intercepts my traffic?

Probably, but if you still want to monitor traffics on your pc maybe use Wireshark instead of fiddler.

**Comment by Soitora** [comment]
> > I had enabled HTTPS snooping on Fiddler, which might be the issue since it I guess intercepts my traffic?
> 
> Probably, but if you still want to monitor traffics on your pc maybe use Wireshark instead of fiddler.

I tried Wireshark but that was without knowing anything, I did see 6 references with AniList GraphQL domain in them

**Comment by KaiserBh** [comment]
> > > I had enabled HTTPS snooping on Fiddler, which might be the issue since it I guess intercepts my traffic?
> > 
> > 
> > Probably, but if you still want to monitor traffics on your pc maybe use Wireshark instead of fiddler.
> 
> I tried Wireshark but that was without knowing anything, I did see 6 references with AniList GraphQL domain in them

How often do you get the rate limiting? Also instead of emailing them I think the fastest way is to join their discord server and write them a message there, usually mods are on and response fast. Maybe they can even tell you how many request you are sending? It also could be how often you are running PlexAniSync?

**Comment by reconman** [comment]
@KaiserBh Just FYI, if you send 10 requests per second, it will also block you. The exact limit is not officially documented.

**Comment by KaiserBh** [comment]
> @KaiserBh Just FYI, if you send 10 requests per second, it will also block you. The exact limit is not officially documented.

Ouhh damn 10 request that's quite low but understandable. Thanks tho i didn't know it was that low.

**Comment by Soitora** [comment]
> Also instead of emailing them I think the fastest way is to join their discord server and write them a message there, usually mods are on and respond fast. Maybe they can even tell you how many request you are sending? It also could be how often you are running PlexAniSync?

I've asked them twice now, first time no reply, second time only got asked if I got users on shared IP then no reply again

**Comment by KaiserBh** [comment]
> > Also instead of emailing them I think the fastest way is to join their discord server and write them a message there, usually mods are on and respond fast. Maybe they can even tell you how many request you are sending? It also could be how often you are running PlexAniSync?
> 
> I've asked them twice now, first time no reply, second time only got asked if I got users on shared IP then no reply again

Well that's unfortunate, out of curiosity have you tried using VPN to sync it? Seem like they rate limit by ip address but I could be wrong. Still doesn't hurt to try unless you did it already then only option is either make a new account and change your iP address lol but hopefully it's not the account that got rate limited.

**Comment by Soitora** [comment]
> Well that's unfortunate, out of curiosity have you tried using VPN to sync it? Seem like they rate limit by ip address but I could be wrong. Still doesn't hurt to try unless you did it already then only option is either make a new account and change your iP address lol but hopefully it's not the account that got rate limited.

Next time I am rate limited and cant sync I'll try 👍🏻
