### ISSUE TITLE
home_user_sync not matching against the correct user

### ISSUE THREAD

**Issue by 46620** [RickDB/PlexAniSync#57]
I have a few different ini files that I use with Tautulli for my friends who watch stuff on Plex. I spent a few days updating my custom_mappings.ini to a yaml file and had nothing sync for quite a while. I tried running the main `PlexAniSync.py` file to update their accounts and it pulled from mine, no matter what was set for `home_username` I've uploaded what the settings.ini looks like in case I messed something up with it.

[settings.ini.txt](https://github.com/RickDB/PlexAniSync/files/6088135/settings.ini.txt)

**Comment by reconman** [comment]
The home_ options are only used if you use authentication_method `myplex`. For `direct`, you'll probably have to provide a token of another user. `myplex` with `home_user_sync = True` basically logs in as admin account and then retrieves a token for the specified `home_username`.

**Comment by 46620** [comment]
I tried that last night, didn't work but it worked this morning. Thank you so much!
