### ISSUE TITLE
Request: Update plex if anilist is higher

### ISSUE THREAD

**Issue by tsukari** [RickDB/PlexAniSync#6]
Is it possible to have plex update when the episode count on anilist is higher?

**Comment by RickDB** [comment]
There currently a safeguard for that so you don't mess up any existing data on AniList, will add a setting for it and when Plex episodes is higher than 0 it will overwrite any AniList entry even it has an higher episode count there.

**Comment by RickDB** [comment]
Updated readme and settings file, make sure to copy over the new setting `plex_episode_count_priority` from the example settings file.
Would set `skip_list_update` to True for your initial sync as well to see if everything lines up properly.
