### ISSUE TITLE
Specify home user with Tautulli sync script (and docker)

### ISSUE THREAD

**Issue by jacobmix** [RickDB/PlexAniSync#60]
The wiki page doesn't seem to mention how to setup syncing for a specific user.
https://github.com/RickDB/PlexAniSync/wiki/Tautulli-sync-script
I tried this myself tho: https://prnt.sc/10r2h72 (Mainly just adding the conditioning of matching a username)
Then for the arguments i added a settings file like this: settings_JacobMIX.ini "{show_name}"
The setting file is in the same folder as the Tautulli sync script.
I just made (file) volume with the settings file: https://prnt.sc/10r2k9c
Note: the Tautulli sync script is in 3rdPartyScripts

I'm also running the docker container for PlexAniSync, but just using a settings file as read only to get home user to not be overwritten.
https://prnt.sc/10r2j5j
Haven't tested it much, but seems to work.

**Comment by Soitora** [comment]
Yeah that's how you specify the user, I did that for myself too but I forgot to mention it here that it should prob be included in the wiki 👍🏻

**Comment by reconman** [comment]
So this is only about documentation?

Btw, if you didn't know, there's also https://hub.docker.com/r/rickdb/tautulli-plexanisync

**Comment by jacobmix** [comment]
> So this is only about documentation?
> 
> Btw, if you didn't know, there's also https://hub.docker.com/r/rickdb/tautulli-plexanisync

Already got Tautulli installed so didn't even bother. Also wasn't that hard to setup. Plus i want it for multiple users.

**Comment by jacobmix** [comment]
A quick then before i close this. Can i just use my Plex-X-Token, and then specify the user? Or will it still pull from what is (admin) has watched?

**Comment by jacobmix** [comment]
Welp, i said what i wanted. Just close this once the changes are made to the wiki.

**Comment by reconman** [comment]
You can use myplex authentication with home_user_sync, then you won't need their token or password.

**Comment by jacobmix** [comment]
Shit. You're right. Don't know why i thought i needed the token to get every users info as admin.
Using a password still logs me in as admin. Will set it up with that now then.

**Comment by jacobmix** [comment]
Nope. Seems to still pull from what i've watched.

**Comment by RickDB** [comment]
Good to hear and closing issue.
