### ISSUE TITLE
Shows With Just Numbers for Titles Generate Errors

### ISSUE THREAD

**Issue by Iyagovos** [RickDB/PlexAniSync#64]
Hello! I just wanted to report an issue I've found, sorry if I'm doing this wrong, I've never posted on GitHub before!

I just started 86: Eighty-Six, which is just called "86" in Plex/TVDB - this causes the sync to generate the following error while running:

"2021-04-12 22:59:23 Error parsing parsing guessit title for: 86 | 86 | 86
Traceback (most recent call last):
  File "C:\Users\MyUser\Documents\PlexAniSync-master\anilist.py", line 272, in match_to_plex
    plex_title_guessit = guessit(plex_title.lower())["title"].lower()
KeyError: 'title'"

Is there anything wrong with the way I'm tagging the episode? Or is this just something that happens with numbered shows?

**Comment by reconman** [comment]
Is there anything in the log after that? The code should normally continue after that error.

**Comment by Iyagovos** [comment]
Yeah, the whole thing completes! 

I did actually correct this, though - matching the show properly made it work. The show is called 86 - Eighty-Six, not just 86, so perhaps could have been that

**Comment by reconman** [comment]
In TVDB it's `86: Eighty Six`, in AniDB it's just `86`.

Both changing the title in Plex or adding a custom mapping work, I think.
