### ISSUE TITLE
Installing Issue

### ISSUE THREAD

**Issue by Wistci** [RickDB/PlexAniSync#66]
I'm trying to install the program but I am stuck at step 4 when trying to drag the requirements folder into python. When I drag it in and try and run it, it say's "unexpected character line after line continuation character". Anyone know a fix to this?

![ab](https://user-images.githubusercontent.com/82051463/115716706-71ab7680-a347-11eb-981f-02887b5809bf.png)

**Comment by reconman** [comment]
There's nothing in the installation guide about `dragging`. You're supposed to enter the command in the command line.

**Comment by Wistci** [comment]
> There's nothing in the installation guide about `dragging`. You're supposed to enter the command in the command line.

I'm not really well-versed in this type of stuff, can you explain what you mean a little easier for me?

**Comment by reconman** [comment]
1. Press Windows + R
2. Enter "cmd"
3. In the new command window, enter `cd C:\Users\yourusername\Downloads\PlexAniSync-master\PlexAniSync-master`
4. Continue with step 4 in the installation guide

**Comment by Wistci** [comment]
Do you possibly have a discord I can use to message you because i'm still slightly confused sorry :/. If you want to message me i'm Wisty#2774
