### ISSUE TITLE
Suddenly every series has 0 watched episodes

### ISSUE THREAD

**Issue by MrDemocracy** [RickDB/PlexAniSync#67]
Since yesterday all my watched series get detected as having 0 watched episodes. I've tried disabling custom mappings, and tried with both AniPlexSync.py and TautulliSyncHelper.py, but it doesn't make any difference.
Is this issue due to something on my end, or does it happen for everyone because of some change Plex has made to their API?

**Comment by Soitora** [comment]
Did you update the script right before this happened?

**Comment by MrDemocracy** [comment]
I didn't. I tried updating after this issue started happening, to see if that would fix it, but it didn't.

**Comment by reconman** [comment]
Did you run pip install after updating? I updated the min version of the Plex API recently.

**Comment by MrDemocracy** [comment]
I haven't been using pip when updating PlexAniSync, I usually just drag and drop the files from github into the installation folder. I had to re-install python since there were some issues with pip, and now after running `pip install -r requirements.txt` it seems to be working again. Thank you 😊
I also just realized that it's possible to specify the config file by running `python PlexAniSync.py "user1_settings.ini"`. I wish I knew this earlier as I have multiple users set up with PlexAniSync, each using their own installation folder. Having to update each user every time there's a new version is very tedious 😅 Is there also a way to specify the log file, so every user doesn't use the same file?

**Comment by reconman** [comment]
> Is there also a way to specify the log file, so every user doesn't use the same file?

Do you mean the failed matches? Currently not.

**Comment by MrDemocracy** [comment]
I was thinking about `PlexAniSync.log` and `PlexAniSync-DEBUG.log`. I've actually never seen any failed matches in `failed_matches.txt`, even though I frequently see `[ANILIST] No match found for title` when running PlexAniSync.py.

**Comment by reconman** [comment]
I forgot about those. You can enable failed match logging by setting this config parameter: https://github.com/RickDB/PlexAniSync/blob/master/settings.ini.example#L28

**Comment by reconman** [comment]
The 2 .log files are also hard-coded.

**Comment by MrDemocracy** [comment]
Well, I guess I can just set up a new installation before running PlexAniSync.py if I ever need a clean log file for a specific user.
Thanks again for helping me getting the syncing working again 😊

**Comment by TheRealRws** [comment]
I too seem to have this problem with having 0 episodes watched. All my modules are up to date.
