### ISSUE TITLE
Favoriting a systemd timer over a cron job

### ISSUE THREAD

**Issue by wisewtf** [RickDB/PlexAniSync#68]
Hello, I'd recommend enhancing the documentation favoriting a systemd timer (on systemd enabled machines) over a cron job as cron tends to be unreliable at best (in my opinion).

It's pretty simple:

1. Create a `anilist-plex-sync.service` inside `/etc/systemd/system/` with your favourite editor:

```service
[Unit]
Description=One-shot execution of Plex to Anilist tracking sync

[Service]
Type=oneshot
User=YOUR_USER
Group=YOUR_USER
WorkingDirectory=YOUR_PLEXANYSYNC_FOLDER_PATH
ExecStart=/usr/bin/python3 /YOUR_PLEXANYSYNC_FOLDER_PATH/PlexAniSync.py
RemainAfterExit=no

[Install]
WantedBy=multi-user.target
```

2. `sudo systemctl daemon-reload`
3. `sudo systemctl enable anilist-plex-sync.service`
4. `sudo systemctl start anilist-plex-sync.service`

5. Create a `anilist-plex-sync.timer` inside `/etc/systemd/system/` with your favourite editor:

```service
[Unit]
Description=Execution timer for Plex Anilist Sync service

[Timer]
OnCalendar=*:0/15 #(This is every 15 minutes, but you can also put in "daily" for example)

[Install]
WantedBy=timers.target
```

6. `sudo systemctl daemon-reload`
7. `sudo systemctl enable anilist-plex-sync.timer`
8. `sudo systemctl start anilist-plex-sync.timer`

You can check if the timer is running with `sudo systemctl list-timers` and it should show this `Mon 2021-05-31 13:38:02 CEST 3min 1s left  n/a                          n/a                anilist-plex-sync.timer      anilist-plex-sync.service`

Let me know if I should make a pull request and update the readme myself.

**Comment by RickDB** [comment]
If you can make a pull request for this would be great.
