### ISSUE TITLE
Maintain "Rewatching" Status in Anilist

### ISSUE THREAD

**Issue by Beannsss** [RickDB/PlexAniSync#69]
Example - I'm re-watching Ping Pong the animation, and PlexAniSync always resets my "Rewatching" status to "Watching" whenever it syncs.

This should be extremely easy to do I would think. I should be able to get this implemented and create a PR for this if that's okay with you.

**Comment by reconman** [comment]
After watching the last episode, it should be set to Completed again, right?

I already have the code prepared, just need to know how to handle this corner case.

**Comment by Beannsss** [comment]
Yeah that part should work, I haven't taken a good look at the code, but I'm assuming it should just be.

new_status = CURRENT
if series.status is REPEATING
   new_status = REPEATING
update_series

Not sure if this helps.

**Comment by reconman** [comment]
My fix probably works, haven't tested it, though. Can you try?

**Comment by Beannsss** [comment]
Worked.

Insignificant, but:

![image](https://user-images.githubusercontent.com/8314499/125815345-7303fd96-16fb-4033-89c3-aa9e772acfd0.png)

**Comment by reconman** [comment]
Fixed with 1c9d92d0db21c1044d6b33d6ab2cf24040a33c6f
