### ISSUE TITLE
Custom mapping does not take precedent over Anilist ID from metadata

### ISSUE THREAD

**Issue by vodkapmp** [RickDB/PlexAniSync#72]
_This issue is not entirely the same as #55, but it is also about manual mappings not being higher priority than Anilist ID when using the Anilist metadata agent._

I have an issue I noticed with Dragonmaid, where S2 episodes are not being marked as played, as season 2 episodes are tagged with the Anilist ID for Season 1 by the Anilist metadata agent.

And as explained in issue #55, setting a manual mapping for S2 doesn't change anything, as S2 is still picked up as having the ID for season 1.

> 2021-08-03 18:18:57 [ANILIST] Series Kobayashi-san Chi no Maidragon has Anilist ID 21776 in its metadata, using that for updating
2021-08-03 18:18:57 [ANILIST] Updating series: Miss Kobayashi's Dragon Maid | Episodes watched: 13
2021-08-03 18:18:57 [ANILIST] Found AniList entry for Plex title: Kobayashi-san Chi no Maidragon
2021-08-03 18:18:57 [ANILIST] Series is already marked as completed on AniList so skipping update
2021-08-03 18:18:57 [ANILIST] Series Kobayashi-san Chi no Maidragon has Anilist ID 21776 in its metadata, using that for updating
2021-08-03 18:18:57 [ANILIST] Updating series: Miss Kobayashi's Dragon Maid | Episodes watched: 4
2021-08-03 18:18:57 [ANILIST] Found AniList entry for Plex title: Kobayashi-san Chi no Maidragon
2021-08-03 18:18:57 [ANILIST] Series is already marked as completed on AniList so skipping update

Manual mappings:

```entries:
  - title: Kobayashi-san Chi no Maidragon
    seasons:
      - season: 1
        anilist-id: 21776
      - season: 2
        anilist-id: 107717

**Comment by reconman** [comment]
If you're using Anilist, shouldn't you have both seasons as seperate Plex shows like when using AniDB?

**Comment by vodkapmp** [comment]
If I was handling my library manually I would yes, but since I use Sonarr for _most_ of my anime, it'll use the tvdb(?) sorting, and thus use seasons.

**Comment by reconman** [comment]
I personally would recommend using the Hama agent instead, which has a giant XML file with mappings between TVDB and AniDB. Works well on my end using Medusa (alternative to Sonarr).

**Comment by vodkapmp** [comment]
Yeah Hama is good, but I used to have a lot of issues with it not being able to pull romaji titles reliably. 
Which is what made me switch to using the Anilist metadata provider, which has never had an issue with this. 
And at this point the sunk cost fallacy is there to make me really not want to switch back to Hama and have to refresh the metadata on hundreds of shows.. 

This isn't really much of an issue, can always do the few issues where this happens manually, but I just assumed the manual mappings would just always be the upmost decider for mapping, as you'd use it to fix any unforseen issues.

**Comment by Soitora** [comment]
I also use TheTVDB mapping, but the most issue I've noticed is just having 40 overrides, but that's a non-issue for me as they're easy to setup. I don't get this error since I don't have AniList ID in Plex

**Comment by DruWasUnavailable** [comment]
Having recently updated from an ancient installation on an old machine from about a year and a half ago to v1.3.13 and manually updated my custom mappings from the old .ini to the new .yml format, I similarly assumed that the custom mappings would take precedent over anything else, as per prior functionality before integration with the AniList metadata agent was added. Is it feasible for custom mappings to always override? Or am I looking at either manually converting my library from TheTVDB mapping over to one plex series per season, changing to an alternative metadata agent, or just looking for an alternative all together?

**Comment by reconman** [comment]
@vodkapmp Can you try the code from the current master branch?

**Comment by vodkapmp** [comment]
Patched my docker image with the changes, can confirm that it works perfectly! @reconman
