### ISSUE TITLE
Custom Mappings not working

### ISSUE THREAD

**Issue by Maremide** [RickDB/PlexAniSync#77]
Hey, Ive got a problem with the custom mappings. Whenever I try to use the custom mappings file the complete thing stops working and the debug log only outputs:

**"2021-10-02 13:25:03,063 INFO PlexAniSync - version: 1.3.14
2021-10-02 13:25:03,064 INFO [MAPPING] Custom map file found: custom_mappings.yaml"**

It works fine without the custom mappings, but I need the file for s2 or higher

**Comment by Soitora** [comment]
Are you having file extensions visible? So it's not really a `custom_mappings.yaml.txt` file? Right click it to show properties, send here.

**Comment by Maremide** [comment]
YAML-Datei (.yaml)

It's actually a yaml file, otherwise PlexAniSync would just ignore it ig, but thats not the case

**Comment by reconman** [comment]
Can you upload the file to this issue?

**Comment by Soitora** [comment]
Uploading would make it easier to debug.

Try running it through a linter to check for issues:
http://www.yamllint.com/

**Comment by Maremide** [comment]
> Try running it through a linter to check for issues: http://www.yamllint.com/

Thanks for that, it's fixed now haha
seems like there was somewhere, a tab or so that made it fail^^
