### ISSUE TITLE
Add community mappings?

### ISSUE THREAD

**Issue by Soitora** [RickDB/PlexAniSync#81]
Maybe someone would be interested in it here, either as a file or as an entry on the wiki?
I follow TheTVDB mapping which I'm sure many on Plex do, so my mapping for example may be of use to others

Maybe a system where multiple people can add/suggest theirs?

**Comment by Raventhicc** [comment]
I and my friend recently started doing that over at https://github.com/mizz141/PlexAniSync-Mappings. Contributions would be appreciated
