### ISSUE TITLE
PlexAniSync for multiple users

### ISSUE THREAD

**Issue by SjioGG** [RickDB/PlexAniSync#85]
I guess this is more of a question than an issue but is there any way to have it sync to two separate Anilist accounts, or run two separate containers with different credentials.

I am running the docker on Unraid and everything works fine for my admin account, but I've been trying to set up a different container for my brother, but with no luck as I am unable to get the plex-token part to work (I tried using tokens from here 'https://plex.tv/devices.xml'). My understanding so far is that the plex-token is unique to the admin account, and the other accounts on the server are sort of "hitching a ride" on that plex-token.

Is there any way to find a plex-token that works? or any other way of authenticating that works with the docker?

I am still very new to the whole Server/Docker thing so I am sorry if I am being too vague or missing any important information.

Thank you in advance!

**Comment by reconman** [comment]
Should be solved now that #73 is implemented.
