### ISSUE TITLE
A confusing console output

### ISSUE THREAD

**Issue by user4302** [RickDB/PlexAniSync#89]
![image](https://user-images.githubusercontent.com/32593782/142261286-df5ed80f-8c76-4149-afae-0c092cf613f2.png)

this yellow text seems to be refering to a series that is not yet released, "Jin Zhan Fashi"
im confused as to why its showing up in the middle of the series "Ajin"

there does not seem to be any updates on my AniList account for this entry (Jin Zhan Fashi)
and idk how its even being listed here if its not et aired.
have i named somethign incorrectly?

there are no problems for me regarding this mesaage as far as i can see.

**Comment by KaiserBh** [comment]
I believe it just searched against anilist, using "Ajin 2" || "Ajin" and the closest match it found was Jin Zhan Fashi.
just fyi anilist search function is not the brightest. 

Most likely "Ajin" since there seem to be 2nd match that it searched through. 

Also just wondering what are you using for metadata?
TVDB?HAMA?
TMDB?

**Comment by reconman** [comment]
That show indeed shows up in the [Anilist API search results](https://anilist.co/graphiql?query=query%20%7B%0A%20%20Page%20(page%3A%201%2C%20perPage%3A%20100)%20%7B%0A%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20total%0A%20%20%20%20%20%20currentPage%0A%20%20%20%20%20%20lastPage%0A%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20perPage%0A%20%20%20%20%7D%0A%20%20%20%20media%20(search%3A%20%22Ajin%22%2C%20type%3A%20ANIME)%20%7B%0A%20%20%20%20%20%20title%20%7B%0A%20%20%20%20%20%20%20%20romaji%0A%20%20%20%20%20%20%7D%09%09%09%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

If we only looked at existing Anilist entries, you couldn't watch a new Anime show in Plex without adding the series to your Anilist first.

**Comment by user4302** [comment]
> I believe it just searched against anilist, using "Ajin 2" || "Ajin" and the closest match it found was Jin Zhan Fashi. just fyi anilist search function is not the brightest.
> 
> Most likely "Ajin" since there seem to be 2nd match that it searched through.
> 
> Also just wondering what are you using for metadata? TVDB? HAMA? TMDB?

at that time i think i was using hama,
right now im using tvdb i believe

**Comment by reconman** [comment]
I would recommend using a custom mapping for Ajin.
