### ISSUE TITLE
 Error parsing parsing guessit title for: 86 | 86 | 86

### ISSUE THREAD

**Issue by user4302** [RickDB/PlexAniSync#90]
![image](https://user-images.githubusercontent.com/32593782/142263870-fff25933-ea6d-45bb-90ab-f1783304ed9e.png)

should i be concerned about this error?
im guesssing its regarding the series titled "86",
but the series seems to get updated normally.

**Comment by reconman** [comment]
It's a special case because the Guessit library, which was built for determining show names based on file names, can't handle `86`. That's because numbers usually are the episode number, not the title of the show.

I'm wondering myself why guessit is even used. @RickDB Do you remember why?

**Comment by RickDB** [comment]
@reconman Guessit was added for fuzzy matching titles and don't think we needed anymore with custom mappings and title corrections.
