### ISSUE TITLE
settings.ini Multiple anime sections not working

### ISSUE THREAD

**Issue by ShoeChicken** [RickDB/PlexAniSync#92]
Ability to use multiple plex sections isn't working properly.
It recognizes that there are 2 sections but only does a check on the first section.
anime_section = Anime|Anime Movies

[logfile.txt](https://github.com/RickDB/PlexAniSync/files/7603842/logfile.txt)

**Comment by ShoeChicken** [comment]
Issue Solved
Add feature for the script to skip an entry if the mappings file fails.

**Comment by reconman** [comment]
Sorry, what exactly was wrong with the mapping file to trigger your bug?
