### ISSUE TITLE
Add variables for "update_if_plex_completely_unwatched" and "update_plex_if_anilist_completed"

### ISSUE THREAD

**Issue by Jerrk** [RickDB/PlexAniSync#93]
PlexAniSync works very well for pushing changes from plex->anilist but doesn't seem to do much in the way of pulling anilist->plex. This is creating some issues for me.

I have been manually updating the anilist tracking for x years and i decided recently to start up a plex server for anime.

every single anime i add to plex will be unwatched by default.

If i run PlexAniSync it will go through my anilist anime list and it will **skip** updating the completed anime so the plex unwatched info is not changed.

For instance:
I set up custom mappings for [Log Horizon](https://anilist.co/anime/17265/Log-Horizon/) from the community custom mappings page
```
  - title: "Log Horizon"
    seasons:
      - season: 1
        anilist-id: 17265
      - season: 2
        anilist-id: 20671
      - season: 3
        anilist-id: 114862
```
I've watched seasons 1 through 3 and have set all 3 as completed on anilist

When plexanisync runs i get this message in the console
```
--------------------------------------------------
[ANILIST] Used custom mapping | title: Log Horizon | season: 1 | anilist id: 17265
[ANILIST] Updating series: Log Horizon | Episodes watched: 1
[ANILIST] Found AniList entry for Plex title: Log Horizon
[ANILIST] Series is already marked as completed on AniList so skipping update
[ANILIST] Used custom mapping | title: Log Horizon | season: 2 | anilist id: 20671
[ANILIST] Updating series: Log Horizon 2 | Episodes watched: 1
[ANILIST] Found AniList entry for Plex title: Log Horizon
[ANILIST] Series is already marked as completed on AniList so skipping update
[ANILIST] Used custom mapping | title: Log Horizon | season: 3 | anilist id: 114862
[ANILIST] Updating series: Log Horizon: Destruction of the Round Table | Episodes watched: 1
[ANILIST] Found AniList entry for Plex title: Log Horizon
[ANILIST] Series is already marked as completed on AniList so skipping update
--------------------------------------------------
```
I marked ep1 of each season as watched in plex manually for it to try updating since this seems to be how the script is supposed to function.

> Unwatched Anime in Plex will not be synced so only those that have at least one watched episode, updates to AniList are only send with changes so need to worry about messing up watch history.

In my scenario i have 900~ anime seasons completely watched and tracked on anilist and i am unable to update the plex watched status since they are all already completed **and** i haven't watched at least one episode in each season within plex.

**I believe i have two requests that will fix this issue:**
1. Set a variable like "update_if_plex_completely_unwatched" true|false that will toggle the behavior of PlexAniSync skipping all anime that has no watched episodes.
2. Set a variable like "update_plex_if_anilist_completed" true|false that will update the plex watched toggle even if the anime is set as completed on anilist

To fix 1. i could of course manually mark all anime as completed, but i have two issues with doing that. 
1. i would have to do this manually for over 700 anime that i have in my plex library, which is doable with shift marking but that is infeasible due to issue...
2. i have a specials folder for most anime that is not always completely watched the same as the seasons are. This would make me have to open each watched anime series and then manually mark the seasons as watched one by one instead of marking the entire anime series as watched.

To fix 2. i could mark every completed anime on anilist as still watching which seems kind of silly and would still need the implementation of 1. to work.

**Comment by reconman** [comment]
I don't really get what `update_if_plex_completely_unwatched` should accomplish.

Also, regarding updating Plex watched episodes based on Anilist watched status, mapping the Plex episodes to Anilist is already a bunch of convoluted code and reversing that mapping is much work.

For now, you could still use the Plex Web interface, but this way:

1. Go to your Anime library
2. In the sort options, change "TV Shows" to "Seasons"
3. Click in the top left of the first season you want to mark watched
4. Once one season is selected, you can just click on the poster to select others
5. Click "Mark as Played"

That way, you can leave out Special seasons and you can mark anything as watched where you're sure.

But strangely, if you display seasons, it won't show you how many episodes are unwatched, as opposed to when you go to the show and view the seasons. So you probably will mark seasons as played unnecessarily.

**Comment by Jerrk** [comment]
it appears i've misunderstood the capabilities of this script, it seems to only be pushing from plex to anilist with no interaction in the way of changing watched status within plex itself.

hopefully that could be added at some point in the future but since my suggestions have a prerequisite of pulling info from anilist into plex i'll close this issue for now.

> In the sort options, change "TV Shows" to "Seasons"

that would indeed be a nicer way to mark seasons as complete but as you said it weird how the seasons do not have any watched markers which is unfortunate.

thanks for the help.
